apiVersion: provisioning.grafana.app/v0alpha1
kind: Repository
metadata:
  name: 'Github'
spec:
  type: github
  github:
    url: 'https://github.com/bnussman/k3s'
    branch: 'main'
    path: 'grafana/dashboards/'
secure:
  token: { create: '{{GRAFANA_GITHUB_PAT}}' }